prgrms-web-devcourse-final-project/WEB3_4_SsamMuDan_BE

- .github/workflows/build_test.yml
- src/main/java/ssammudan/cotree/global/response/BaseResponse.java
- src/main/java/ssammudan/cotree/global/response/aop/HttpResponseStatusAspect.java
<br/>
#6 
<br/>
- BaseResponse, data 항목 null 이라도 반환하도록 변경
- Controller Layer 응답 시, BaseResponse 의 Httpstatus 에 따라 status 변경되도록 AOP 적용
- 테스트 케이스1) HttpStatus : Create
- 테스트 케이스2) data 추가
- 테스트 케이스3) Exception 발생 후, `GlobalExceptionHandler` 에서 컨트롤 되는 것 확인
- 테스트 코드
```java
@RestController
@RequestMapping("/api/v1/member")
@RequiredArgsConstructor
public class MemberController {
@GetMapping("/1")
public BaseResponse<Void> test1() {
return BaseResponse.success(SuccessCode.TEST1);
}
@GetMapping("/2")
public BaseResponse<Dto> test2() {
Dto testDto = new Dto(1, "테스트");
return BaseResponse.success(SuccessCode.TEST2, testDto);
}
@GetMapping("/3")
public BaseResponse<Void> failTest1() {
throw new GlobalException(ErrorCode.NOT_FOUND_URL);
}
}
@Getter
@RequiredArgsConstructor(access = …
```
> [REFACTOR] : BaseResponse 수정 및 AOP 추가

- src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
- src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookRequest.java
- src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
- src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
- src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
- src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
- src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
- src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
- src/test/java/ssammudan/cotree/model/education/supporter/DataJpaTestSupporter.java
- src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
<br/>
close #20
<br/>
- 테스트 코드 수정
- 기존 반복 테스트(@RepeatTest)의 트랜잭션에서 발생하는 더미 데이터간 충돌 해결을 위해 테이블 초기화 메서드(setup) 추가
- @BeforeEach 및 더미 데이터 사용 테스트 메서드 내 강제 명시
- TechBook 페이징 목록 조회 기능 구현
- 리턴 타입 Page, 추후 팀 협의 후 커스텀 템플릿 활용 고려
- Repository - Service - Controller 기능 구현 및 테스트 코드 작성
<br/>
<br/>
<br/>- messages.properties 적용 이전 고려 삭제
> feat: #ET-3 TechBook 페이징 목록 조회 기능 구현

- .github/workflows/deploy.yml
- Dockerfile
- build.gradle
- src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
- src/main/resources/application.yml
- src/main/resources/config/prod/application-prod_db.yml
**[FEAT] : CD 구축을 위한 Dockerfile 및 배포 설정 추가**
<br/>
#28
<br/>
- **Dockerfile** 및 **deploy.yml** 파일 추가하여 배포 자동화와 CD 파이프라인 구축을 위한 설정 적용
- **application-prod_db.yml**에서 `ddl-auto: update`로 수정하여 서버 실행 시 자동으로 테이블 및 데이터 생성 구현
- **application.yml**에 `config.import - optional:file:.env[.properties]` 추가하여 서버에서 자동으로 .env 파일을 적용하도록 설정
- **build.gradle**에서 QueryDSL 버전 5.0.0에서 5.1.9로 업그레이드하여 소나큐브 지적 및 배포 자동화 오류 해결
- **spring-boot-starter-actuator** 의존성 추가하여 애플리케이션 상태 모니터링 및 `/actuator/health` API를 통한 정상 작동 여부 확인
- **SecurityConfig**에 `/actuator/health` 접근 허용 설정 추가하여 누구나 해당 엔드포인트에 접근 가능하도록 설정
<br/>
CD 자동화 설정 중 발생한 부분을 임의로 수정했습니다. 수정된 내용 중 문제가 될 수 있는 부분이나 개선이 필요한 부분이 있으면 피드백 부탁드립니다. 수정 사항을 인지해 주셨으면 좋겠습니다.
<br/>
> [FEAT] : CD 구축을 위한 Dockerfile 및 배포 설정 추가

- src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
- src/main/java/ssammudan/cotree/domain/comment/dto/CommentRequest.java
- src/main/java/ssammudan/cotree/domain/comment/service/CommentService.java
- src/main/java/ssammudan/cotree/domain/comment/service/CommentServiceImpl.java
- src/main/java/ssammudan/cotree/domain/comment/type/CommentCategory.java
- src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
- src/main/java/ssammudan/cotree/global/response/ErrorCode.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/common/comment/entity/Comment.java
<br/>
#49 
<br/>
- `Resume` (이력서), `Community` (커뮤니티 게시글) 에 댓글을 남기는 기능을 추가하였습니다.
- JPA 를 사용하였습니다.
- 로그인 정보는 하드코딩으로 진행되어있습니다.
- 추후, 로그인 기능 merge 시, 업데이트 예정입니다.
- 대댓글을 저장할 때, parent_id 만 있으면 사실 조회가 가능하지만, 추후 조회시 편의성을 위해 각 item 의 id 를 같이 넣어두었습니다.
- 추후 기능 구현에 따라, 저장 로직이 변경될 수 있습니다.
- 또한 단방향 매핑만 추가되어있는데, 아마 삭제 기능이나 조회 기능 개발하면서 양방향 매핑이 추가될 수 있습니다.
<br/>
<br/>
<br/>
> [FEAT] #RRDC-1, #CBDC-1 댓글 작성 기능 구현

- src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectCreateRequest.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectCreateResponse.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/infra/s3/S3Directory.java
- src/main/java/ssammudan/cotree/model/project/devposition/entity/ProjectDevPosition.java
- src/main/java/ssammudan/cotree/model/project/project/entity/Project.java
- src/main/java/ssammudan/cotree/model/project/techstack/entity/ProjectTechStack.java
- src/test/java/ssammudan/cotree/domain/project/controller/ProjectControllerTest.java
- src/test/java/ssammudan/cotree/domain/project/service/ProjectServiceImplTest.java
<br/>
#42 
<br/>
- 프로젝트 생성 API 구현
- member, security 적용되면 controller에서 로그인 한 member 받아올 예정
- 빌더 패턴 적용
- S3Directory enum class에 project 경로 추가
- 이미지 파일을 request에 담아서 처리가 불가능하여 controller에서 따로 받게 구현(포스트맨 사용 양식 이미지 첨부)
- request의 Content-Type을 application/json으로 지정해야 합니다.
<br/>
<br/>
> [FEAT] #PT-2 프로젝트 생성

- src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
- src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
- src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
- src/main/java/ssammudan/cotree/domain/resume/controller/ResumeController.java
- src/main/java/ssammudan/cotree/domain/upload/controller/FileUploadController.java
- src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
- src/main/resources/config/prod/application-prod_auth.yml
- src/main/resources/config/prod/application-prod_server.yml
<br/>
#60 
<br/>
- Security 인가 Path 설정 진행하였습니다. (`SecurityConfig`)
- `prod` 프로파일에서 누락된 설정 추가하였습니다. (`application-prod_db.yml`, `application-prod_auth.yml`)
- 로그인 된 회원의 ID 를 받아와야 하는 부분 (하드코딩 된 부분) 인증 받도록 변경하였습니다.
- `@AuthenticationPrincipal CustomUser customUser`
- `Comment`, `Community`, `FileUpload`, `Project`
<br/>
<br/>
<br/>
> [REFACTOR] : Security 인가 path 설정 및 누락 pord profile 설정 추가

- src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
- src/main/java/ssammudan/cotree/domain/project/dto/HotProjectResponse.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectCreateRequest.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectInfoResponse.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
- src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
- src/main/java/ssammudan/cotree/global/response/ErrorCode.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepository.java
- src/main/java/ssammudan/cotree/model/project/devposition/repository/ProjectDevPositionRepository.java
- src/main/java/ssammudan/cotree/model/project/membership/entity/ProjectMembership.java
- src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepository.java
- src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepository.java
- src/main/java/ssammudan/cotree/model/project/techstack/repository/ProjectTechStackRepository.java
<br/>
#71 #73  
<br/>
- 특정 프로젝트의 상세 정보를 조회할 수 있도록 기능 구현
- 프로젝트의 주요 정보(제목, 내용, 사진, 생성자 이름, 시작일, 마감일, 연락처 등) 반환
- 모집 분야, 기술 스택, 인재상, 좋아요 개수, 조회수, 모집 여부 추가
- 프로젝트 생성자 여부 확인 기능 추가
- 프로젝트 참가 여부 확인 기능 추가 (JOINED 상태만 해당)
- 사용자가 좋아요를 눌렀는지 여부 확인 기능 추가
- 프로젝트 생성 api 스웨거 문서 가독성 향상을 위해 스키마 적용
- 하나의 api로 로그인 여부 상관없이 조회 가능하게 구현
<br/>
- `isParticipant`, `isOwner`, `isLiked` 로직의 가독성 및 효율성 검토 필요합니다.
- 조회 로직 개선 사항 있으면 부탁드립니다! 
<br/>
<br/>
> [FEAT] #PTDL-2 #PTD-1 프로젝트 상세 조회

- src/main/java/ssammudan/cotree/domain/comment/controller/CommentController.java
- src/main/java/ssammudan/cotree/domain/comment/dto/CommentResponse.java
- src/main/java/ssammudan/cotree/domain/comment/service/CommentService.java
- src/main/java/ssammudan/cotree/domain/comment/service/CommentServiceImpl.java
- src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
- src/main/java/ssammudan/cotree/global/response/ErrorCode.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/common/comment/entity/Comment.java
- src/main/java/ssammudan/cotree/model/common/comment/repository/CommentInfoProjection.java
- src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepository.java
- src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/common/comment/repository/CommentRepositoryImpl.java
- src/main/java/ssammudan/cotree/model/community/category/entity/CommunityCategory.java
- src/main/java/ssammudan/cotree/model/community/community/entity/Community.java
<br/>
#54 
<br/>
- 이력서와 커뮤니티 글의 댓글을 조회하는 기능을 구현하였습니다.
- 통합으로 진행하였습니다.
- QueryDSL 을 활용하였습니다.
- 테스트 코드는 추후 작성 예정이며, 로컬 환경 수동 테스트는 진행 완료하였습니다.
- 댓글과 대댓글이 존재하며, 댓글은 페이지네이션 적용, 대댓글은 전체 조회로 구성하였습니다.
- 내부 로직은 최적화를 위해, 다음 플로우를 적용하였습니다.
- (itemId 로 댓글 size 만큼 가져오기) -> (가져온 댓글 id 들을 활용해, 대댓글과 댓글 정보 전체 find) -> (parent_id 유무로 댓글/대댓글 정리 및 sorting) -> 응답
<br/>
- 생각하고 보니, 댓글/대댓글 정리하고 sorting 하는 작업이 queryDSL 이 있는 repository 레이어에서 진행되었는데, 생각하고 보니 service 레이어로 옮기는게 좋은 것 같습니다. 해당 의견 검토 부탁드립니다!
<br/>
<br/>
> [FEAT] : #CBDC-2, #RRDC-2 댓글 조회 기능 구현

- src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
- src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
- src/main/java/ssammudan/cotree/domain/education/type/SearchEducationSort.java
- src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
- src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
- src/main/java/ssammudan/cotree/domain/review/type/SearchReviewSort.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
- src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepository.java
- src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
- src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
- src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
- src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
- src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java
- src/test/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryTest.java
<br/>
close #87
<br/>
- TechBook, 교육 컨텐츠 리뷰(TechEducationReview) 목록 조회 시 정렬 파라미터 변경
- Enum 타입 파라미터 활용
- 각 정렬 조건은 내림차순 기반, 생성일자(createdAt)이 아닐 경우 생성일자 최신순 정렬 조건도 포함
- 기존 정렬 조건에서 좋아요(Like) 누락 사항 추가
<br/>
<br/>
<br/>
> [BUG] TechBook, 리뷰(수강평) 정렬 조건 누락 수정 등

- src/main/java/ssammudan/cotree/infra/s3/S3Uploader.java
<br/>
#104 
<br/>
- Server 측 S3 파일 저장 시, Encoding 하여 저장하는 방식이, 맞지 않아 presigned url 로 fe(브라우저) 에서 403 발생 확인
- encoding 하지 않고 바로 저장하도록 수정. 단, 특수문자는 위험성이 있어, _ 로 치환
- 개인 S3 로 업로드 및 브라우저에서 로드 확인 완료.
<br/>
<br/>
<br/>
> [BUG] S3 파일 업로드 시, URL Encoding 문제 수정

- src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
- src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
- redirect 용 id 값 return 하도록 변경.
- 기존 : return null;
<br/>
Closes: #98 
<br/>
- 커뮤니티 글 작성 성공 후, ID 값 Return 누락 해결
- 기타, 들여쓰기 컨벤션 수정되었습니다.
<br/>
<br/>
<br/>
> [BUG] 커뮤니티 글 작성 성공 후, ID 값 Return 누락 해결

- src/main/java/ssammudan/cotree/infra/s3/S3Directory.java
- src/main/resources/db/seed/dev/R__A_insert_seed.sql
- src/main/resources/db/seed/prod/R__A_insert_seed.sql
<br/>
Closes #118 
<br/>
- 기존이미지가 다운로드하는 이미지 url이였어서 s3에 업로드한 이미지 url로 변경했습니다.
- 서버db의 techstack image url 변경 완료했습니다.
- 프론트측에서 이미지 잘 나오는거 확인했습니다.
<br/>
> [FIX] techstack image url들 s3 이미지로 변경

- src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
- src/main/java/ssammudan/cotree/model/community/community/entity/Community.java
- src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java
- src/main/resources/db/migration/V2.2__add_column_community_thumbnail_image.sql
- src/test/java/ssammudan/cotree/integration/factory/CommunityDataFactory.java
<br/>
#23 
<br/>
- 글 작성 시, 썸네일 이미지 추출하도록 추가하였습니다.
- 상세 조회시에도 썸네일이 필요하기 때문에, 썸네일 이미지용 컬럼을 하나 table 에 추가하였습니다.
- 글 목록 조회 시, 이미지는 제거 후, 출력되도록 서비스 로직을 추가하였습니다.
- 리스트 조회 시, 이미지는 따로 보여줄 필요가 없기때문에 삭제하였습니다.
<br/>
- 기존 record 형 response 객체에 content 를 수정하게 하였더니, 불변성에 의해서 새로운 BoardListDetail 를 생성하는 정적 팩터리 메서드가 생겼습니다...
- 사실 이렇게 되면 content 에 대해서는 불변성을 지킬 필요가 없으니, record 객체에서 일반 class 로 변경하고 content 제외 나머지 필드에 대해서 final 로 불변성을 보장하는게 더 나은방향일지 고민이 됩니다.
- 
<br/>
<br/>
> [FEAT] : #CB-1 커뮤니티 글 작성 대표 이미지 자동 추출 기능 추가

- src/main/java/ssammudan/cotree/domain/category/controller/CategoryController.java
- src/main/java/ssammudan/cotree/domain/category/dto/CommunityCategoryResponse.java
- src/main/java/ssammudan/cotree/domain/category/service/CategoryService.java
- src/main/java/ssammudan/cotree/domain/category/service/CategoryServiceImpl.java
- src/main/java/ssammudan/cotree/domain/community/dto/CommunityRequest.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/test/java/ssammudan/cotree/domain/community/dto/CommunityRequestTest.java
- src/test/java/ssammudan/cotree/domain/community/service/CommunityServiceImplTest.java
<br/>
#142 
<br/>
- 커뮤니티 글 카테고리 조회 기능 추가되었습니다. (리스트 조회 형식)
- 글 작성 시, request body 값이 변경되었습니다.
- 기존 : request body 內 community category 를 String 값으로 전달
- 변경 : communityCategoryId 로 전달
- 기타, 줄바꿈 컨벤션 안맞는 것 수정 (예전에 작성된 테스트 코드)
<br/>
<br/>
<br/>
> [FEAT] : #CC-1 커뮤니티 카테고리 조회 기능 추가 구현 및 작성 리팩토링

- src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
- src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java
<br/>
#133 
<br/>
- FE 요청사항으로, community 조회 시, 작성자의 이미지url 을 같이 return 하도록 추가하였습니다.
- record 객체 내부 데이터를 바꾸기 위해, 정적 팩터리 메서드로 새 인스턴스를 생성하던 로직을 `with` 사용으로 변경하였습니다.
<br/>
- N/A
<br/>
<br/>
> [REFACTOR] Community Board 조회 (리스트, 단건) 시, 프로필 이미지 추가 return

- src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
- src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java
- src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
- src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
- src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
<br/>
- 회원 업데이트(PUT)시에 DTO와 Entity의 필드값이 잘못 매핑되어 수정이 의도하지 않은 형태로 이루어지는 버그가 발생했습니다.
- 해당 부분을 수정하고 프론트엔드의 요구사항을 반영하여 회원 조회 시 nickname 뿐만 아니라 username도 추가하여 반환하도록 수정하였습니다.
<br/>
- 업데이트 로직에서 잘못된 부분 수정했습니다~
<br/>
<br/>
<br/>
> [Bug] : 회원 업데이트 버그 수정

- src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
- src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
- src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
- src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
- src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewResponse.java
- src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/ErrorCode.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/entity/TechBook.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
- src/main/java/ssammudan/cotree/model/payment/order/history/repository/OrderHistoryRepository.java
- src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
- src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
- src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
- src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
- src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
- src/test/java/ssammudan/cotree/integration/WebMvcTestSupporter.java
…tents-add-field
<br/>
close #150 
<br/>
- TechBook 응답 DTO 필드 정리
- 누락 데이터: 프로필 이미지 URL, 구매 여부(isPaymentDone) 필드 추가
- 리포지토리에서 Querydsl 프로젝션 사용(* TechTube 참조)
- 기존 메서드 변경/삭제에 따른 테스트 코드 제거 및 수정
- 교육 컨텐츠 리뷰(TechEducationReview) 응답 시 프로젝션 사용으로 변경
- 교육 컨텐츠 리뷰 작성 시 구매 이력 확인 로직 추가
- 로그인한 회원이 리뷰 작성 대상 제품 구매 기록이 없다면 예외
<br/>
<br/>
<br/>…tents-add-field
> [Refactor] TechBook, 수강평(리뷰) 응답 객체 수정 등

- src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectDevPositionResponse.java
- src/main/java/ssammudan/cotree/domain/project/dto/ProjectInfoResponse.java
- src/main/java/ssammudan/cotree/domain/project/dto/UpdateProjectPositionRequest.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
- src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/project/devposition/entity/ProjectDevPosition.java
- src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java
<br/>
#168 
<br/>
- 프로젝트 상세 조회에서 직무별 모집 인원을 수정하게 구현했습니다.
- 프로젝트는 모집중이어야하고 생성자만 수정이 가능합니다.
- 직무별 모집 인원 수정을 위해 프로젝트 상세조회에서 projectDevPositionId도 추가하여 전달하였습니다.
<br/>
> [FEAT] #PTDD-1 프로젝트 직무별 모집 인원 수정

- src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
<br/>
close #191 
<br/>
- 결제 전 Redis에 저장해놓는 결제 정보 유지 시간 단위가 리팩토링 과정 중 millis로 적용됨
- 기존 의도(10분 유지) 적용을 위해 minute로 수정
<br/>
<br/>
<br/>
> [BUG] : Redis 저장 결제 정보 시간 단위 수정

- src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
- src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryService.java
- src/main/java/ssammudan/cotree/domain/order/service/OrderHistoryServiceImpl.java
- src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
- src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
- src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
<br/>
close #195 
<br/>
- Redis에 저장된 검증용 결제 데이터를 역직렬화하여 조회할 때 타입 캐스팅 문제 해결
- OrderHistory 생성 및 상태 반영 저장(결제 성공 or 결제 실패) 트랜잭션 분리
- 결제 승인 API 호출 예외 발생 시에도 결제 기록은 DB에 반드시 저장하기 위함
- 기타 코드 리팩토링
<br/>
<br/>
<br/>
> [BUG] 결제 로직 중 Redis 저장 데이터 역직렬화 에러 등 수정

- src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
- src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
- src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
- src/main/java/ssammudan/cotree/global/response/SuccessCode.java
- src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryCustom.java
- src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryImpl.java
<br/>
#192 
<br/>
- 내가 좋아요한 Community 목록을 조회하는 기능 구현
- 페이지네이션 응답이고, default size 는 16 입니다.
<br/>
- 조회 시작 테이블을, `community` 에서 진행할까, `like` 에서 진행할까 고민이 되었는데, `like` 에서 시작하게 되었습니다.
- 이유는, like entity 쪽이, `회원이 좋아요 누른 커뮤니티 게시글들` 을 조회하는 목적과 책임에 더 어울린다고 판단되었습니다.
<br/>
<br/>
> [FEAT] #CBL-1 커뮤니티 좋아요 글 목록 조회

- build.gradle
- src/main/java/ssammudan/cotree/domain/community/dto/CommunityRequest.java
- src/test/java/ssammudan/cotree/domain/community/controller/CommunityControllerTest.java
- src/test/java/ssammudan/cotree/domain/community/service/CommunityServiceImplTest.java
- src/test/java/ssammudan/cotree/integration/SpringBootTestSupporter.java
- src/test/java/ssammudan/cotree/integration/security/WithCustomMember.java
- src/test/java/ssammudan/cotree/integration/security/WithCustomMemberSecurityContextFactory.java
- src/test/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryImplTest.java
- src/test/java/ssammudan/cotree/model/community/category/repository/CommunityRepositoryTest.java
<br/>
#217 
<br/>
- Community Controller 테스트를 추가하였습니다.
- 기타 누락된, 내가 좋아요 누른 Community 글 리스트 조회와 관련된 단위/통합 테스트 추가하였습니다.
- jacoco 관련 설정을 추가하였습니다.
- 현재는 설정만 추가하고, 커버리지에 따른 build 성공/실패를 false 로 꺼두었습니다.
- 테스트 한 레이어는, `Controller`, `Service`, `Repository`, `RequestDto` 입니다.
Controller : 요청이 접수되면 올바르게 response 하는지.
Service : service 로직이 재대로 실행 되는지
Repository : db 에 조회를 잘 하는지
RequestDto : 입력된 Dto 의 값이 설정된 유효성을 통과하는지
- 이런 목표로 작성되었습니다.
<br/>
- controller 테스트 시, Spring Security 가 있는 상태에서 진행하기 위해, `WithCustomMember` 라는 어노테이션을 만들었습니다.
- 내부적으로, `WithCustomMemberSecurityContextFactory` 에서는 신규 Member를 만들어 DB에 저장, Security Context 에 추가 하도록 구성하였습니다.
- 해당 annotation 을 통한 member 생성은 class 의 @transaction 범위에 들어가지 않아, @AfterEach 를 통해, 저장된 member를 삭제하도록 tearDown() 메서드를 구현하였습니다.
- 결과적으로는, controller 에서 service 를 …
> [TEST] Community test code 추가

- src/main/java/ssammudan/cotree/global/config/security/filter/JwtAuthenticationFilter.java
- src/main/java/ssammudan/cotree/global/config/security/user/CustomUserDetailsService.java
- refreshToken을 사용한 인증정보 확인 메서드 구현
<br/>
#230 
<br/>
- 인증정보가 없다면 예외를 던져서 프로그램이 중단되지 않고 null을 반환하여 다음 필터로 넘어갈 수 있도록 로직을 수정하였습니다.
<br/>
<br/>
<br/>
> [FEAT]: CustomUserDetailsService.loadUserByRefreshToken 구현

- src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
- src/main/resources/db/migration/V3.2__add_index_recruitment_resume.sql
<br/>
#265
<br/>
P95 서버 기준 500ms 이상 나오는 API 애 대해 집중적으로 성능 최적화
[채용] 이력서 리스트 조회순, 직무 조회
[채용] 이력서 리스트 조회순 조회
[채용] 이력서 초기 리스트 조회
- group by 제외 하고 distinct 적용 
- order by 절에 사용되는 칼럼에 인덱스 적용
로컬 기준 220 으로 형성되던 이력서 초기 리스트 조회와 이력서 리스트 조회순 조회가 
95% Line 기준 120~130 으로 감소 (약 40%~50% 감소)
Explain 에서도 `Using filesort` 제거
<br/>
<br/>
<br/>
> [REFACTOR] 채용 도메인 이력서 조회 성능 개선
