src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
src/main/java/ssammudan/cotree/model/member/member/entity/MemberFactory.java
src/test/java/ssammudan/cotree/domain/member/controller/MemberControllerTest.java

<br/>
#3
<br/>
- MemberEntity 구현(DB 제약조건 매핑)
- SingUp(회원가입 기능 구현)
<br/>
<br/>
- 테스트 케이스 1) 회원가입 성공
- 테스트 케이스 2) 회원가입 실패(유효하지 않은 이메일)
- 테스트 케이스 3) 회원가입 실패(중복 회원)
<br/>
<br/>
<br/>

[FEAT] : ERD 기준 Member entity 작성 및 회원가입 기능 구현

---

.gitignore
terraform/main.tf
terraform/outputs.tf
terraform/providers.tf
terraform/variables.tf

<br/>
Closes #4
<br/>
- 보안과 관련된 terraform파일 ignore처리 (gitignore)
- AWS 인프라 설정 (VPC, 서브넷, 보안 그룹, 출력값 정의)
- 사용 OS: Ubuntu Server 24.04 LTS (HVM)
- 탄력적IP를 사용하여 api-server의 ip값을 일정하게 지정했습니다.
- SSH 접속을 위한 키페어 설정
- EC2 두대 운영하는데 매니저님 컨펌 받았습니다.
- 볼륨과 용량은 매니저님이 추천하신대로 설정했습니다.
<br/>
- Terraform 설정에서 보안 그룹과 VPC 설정 등이 올바르게 이루어졌는지 확인 부탁드립니다.
<br/>

[FEAT] : 테라폼을 이용한 AWS 구축

---

src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java

<br/>
close #43 
<br/>
- EducationLevel 엔티티와 연관관계를 갖는 엔티티의 테스트에서 발생하는 문제 해결
- Fixture Monkey를 사용한 랜덤 인스턴스 생성 시 파라미터를 강제로 명시
<br/>
<br/>
<br/>

[FIX] TechBook 테스트 관련 수정

---

src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
src/test/java/ssammudan/cotree/model/education/level/repository/EducationLevelRepositoryTest.java
src/test/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryTest.java

<br/>
#43 
<br/>
- Fixture Monkey를 사용한 랜덤 인스턴스가 @RepeatedTest에서 충돌 발생(하나의 트랜잭션에서 반복 수행, 제약 조건 충돌)
- @RepeatedTest 주석 처리 -> @Test 일괄 적용
<br/>
<br/>
<br/>

[BUG] @RepeatedTest 제거, @Test 적용

---

src/main/java/ssammudan/cotree/domain/category/controller/CategoryController.java
src/main/java/ssammudan/cotree/domain/category/dto/TechStackResponse.java
src/main/java/ssammudan/cotree/domain/category/service/CategoryService.java
src/main/java/ssammudan/cotree/domain/category/service/CategoryServiceImpl.java
src/main/java/ssammudan/cotree/domain/resume/dto/query/TechStackInfo.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/test/java/ssammudan/cotree/domain/category/CategoryTestHelper.java
src/test/java/ssammudan/cotree/domain/category/controller/CategoryControllerTest.java

<br/>
Close #37 
<br/>
- 기술 스택 조회 API 입니다
- 기술 스택 조회 API 를 호출하면 전체 기술 스택이 리스트에 담겨 반환됩니다 
<br/>
<br/>
<br/>

[FEAT] #CS-1 기술 스택 검색

---

src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryCustom.java
src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java

<br/>
#36 
<br/>
- BoardId로 해당 글의 상세 내용을 응답하는 API 입니다.
- QueryDSL 로 작업되었습니다.
- 내부적으로, like count 는 subquery 로 작성되었습니다.
- API 우선작업으로, 글 상세 조회 시, 조회수가 업데이트 되는 기능은 아직 처리되지 않았습니다.
- #39 에서 진행 예정
- 테스트 코드 또한 API 우선 작업 후, 일괄 처리 예정입니다.
- 별도 이슈 작성 후, 전체 Line coverage 확인 예정.
<br/>
<br/>
<br/>

[FEAT] : #CBD-1 커뮤니티 글 상세 조회 API 

---

src/main/java/ssammudan/cotree/domain/comment/service/CommentServiceImpl.java

<br/>
#57 
<br/>
- 코드 머지되며, `CommentServiceImpl` 에서 없던 Errorcode 를 참조하던 것을 확인, 수정하였습니다.
<br/>
<br/>
<br/>

[BUG] : Compile 오류 수정

---

src/main/resources/config/prod/application-prod_db.yml

<br/>
#63 
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
<br/>

[BUG] prod 환경 redis 환경 yml 누락 해결

---

src/main/java/ssammudan/cotree/infra/s3/S3Directory.java

<br/>
#80 
<br/>
<br/>
<br/>
<br/>

[FEAT] : education_tech book s3 upload 용 category 생성

---

src/main/java/ssammudan/cotree/infra/s3/S3Uploader.java
src/main/resources/config/dev/application-dev_server.yml
src/main/resources/config/prod/application-prod_server.yml

<br/>
#83 
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
<br/>

[BUG] : S3 업로드 수정

---

src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepository.java

<br/>
#78 #55 
<br/>
- 메인 페이지 HOT 프로젝트 조회 API 구현
-  페이지네이션 적용
- 프로젝트 페이지 HOT 프로젝트 조회 API 구현
- 기존에는 일반 프로젝트 목록과 함께 조회하려 했으나, HOT 프로젝트는 고정된 데이터이므로 캐싱을 고려하여 별도 API로 구현
- 캐싱 작업 추후에 할 예정입니다. 
<br/>
- 의도한 방법보다 더 좋은 방법이 있거나 의견 있으시면 공유 부탁드립니다!
<br/>

[FEAT] #MPTH-1, #PTH-1 HOT한 프로젝트 구현(메인페이지, 프로젝트 페이지 별도)

---

src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepositoryImpl.java

<br/>
Closes #99 
<br/>
- `isOwner` 필드 추가. 이글의 주인인지 여부 boolean
- 'author' 필드 닉네임 반환하도록 변경. 기존 : 이름 반환
- 기타 줄바꿈 컨벤션 적용
<br/>
<br/>
<br/>

[BUG] : 커뮤니티 글 상세 조회 응답 수정 

---

src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
src/main/java/ssammudan/cotree/domain/education/techtube/controller/TechTubeController.java
src/main/java/ssammudan/cotree/domain/education/techtube/dto/TechTubeRequest.java
src/main/java/ssammudan/cotree/domain/education/techtube/dto/TechTubeResponse.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeService.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeServiceImpl.java
src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/education/techtube/techtube/repository/TechTubeRepositoryCustom.java
src/main/java/ssammudan/cotree/model/education/techtube/techtube/repository/TechTubeRepositoryImpl.java
src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
src/test/java/ssammudan/cotree/domain/education/techtube/controller/TechTubeControllerTest.java
src/test/java/ssammudan/cotree/domain/education/techtube/service/TechTubeServiceTest.java
src/test/java/ssammudan/cotree/integration/DataJpaTestSupporter.java
src/test/java/ssammudan/cotree/integration/SpringBootTestSupporter.java
src/test/java/ssammudan/cotree/integration/WebMvcTestSupporter.java
src/test/java/ssammudan/cotree/model/education/techtube/category/repository/TechTubeEducationCategoryRepositoryTest.java
src/test/java/ssammudan/cotree/model/education/techtube/techtube/repository/TechTubeRepositoryTest.java

<br/>
close #85 
<br/>
- TechTube API 조회 기능 구현
- TechBook API 형태와 동일하게 구현
- 테스트 코드 추가
<br/>
<br/>
<br/>

[FEAT] TechTube API 조회 구현

---

src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
src/main/resources/db/migration/V2.1__add_unique_constraints_to_member.sql
src/main/resources/db/seed/dev/R__B_insert_member_seed.sql

<br/>
This PR resolves #97
<br/>
- unique 제약조건 추가
- 어플리케이션단에서는 DB 에러로 처리
<br/>
- existsby로 매번 확인하자니 unique 컬럼 3개마다 쿼리를 날려야해서 간단하게 처리 했습니다~
- 혹시 이슈 생기면 보완하겠습니다!
<br/>
<br/>

[Bugfix] : 회원가입 시 중복 회원가입 버그 수정

---

src/main/java/ssammudan/cotree/domain/community/controller/CommunityController.java
src/main/java/ssammudan/cotree/domain/community/dto/CommunityRequest.java
src/main/java/ssammudan/cotree/domain/community/dto/CommunityResponse.java
src/main/java/ssammudan/cotree/domain/community/dto/valid/CommunityContent.java
src/main/java/ssammudan/cotree/domain/community/dto/valid/CommunityTitle.java
src/main/java/ssammudan/cotree/domain/community/service/CommunityService.java
src/main/java/ssammudan/cotree/domain/community/service/CommunityServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/community/community/entity/Community.java
src/main/java/ssammudan/cotree/model/community/community/repository/CommunityRepository.java

<br/>
#90 
<br/>
- 글 수정 기능이 추가되었습니다.
- 전체 글 데이터 request -> entity 조회 -> 내용 수정 -> duty checking 으로 변경 영속성 반영
- 글 삭제 기능이 추가되었습니다.
- 유효성 검증 후, 삭제 처리 (hard delete 정책 적용)
- 글 조작 (수정, 삭제) 시, 유효성 검증 (글 존재 유무, 작성자 인지 아닌지)을 공통 메서드로 처리하였습니다.
- 글 수정 및 생성 시 각 필드에 대한 같은 유효성 검증을 진행하기 때문에, custom annotation 을 만들어 적용하였습니다.
- 기타 줄바꿈 convention 확인
- [CHORE] : community 와 comment 오류 메세지의 상태를 restfull 하게 수정하였습니다.
<br/>
<br/>
<br/>

[FEAT] #CBMC-1, #CBD-1 커뮤니티 글 수정/삭제 기능 구현

---

src/main/java/ssammudan/cotree/domain/resume/controller/ResumeController.java

<br/>
#111 
<br/>
- 인증 적용 전 잔존한 더미데이터 및 파라미터 제거
<br/>
<br/>

[BUG] 이력서 작성 시 레거시 더미데이터 잔존 수정

---

src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/project/project/entity/Project.java

<br/>
#115 
<br/>
- 프로젝트 모집 상태 변경
<br/>
- PATCH를 사용 안하기로 했었는지 정확히 기억이 나지 않습니다. 필요시 PUT으로 수정하겠습니다.
<br/>

[FEAT] #PTDS-1 프로젝트 모집 상태 변경

---

src/main/java/ssammudan/cotree/domain/category/controller/CategoryController.java
src/main/java/ssammudan/cotree/domain/category/dto/EducationCategoryResponse.java
src/main/java/ssammudan/cotree/domain/category/service/CategoryService.java
src/main/java/ssammudan/cotree/domain/category/service/CategoryServiceImpl.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java

<br/>
#126 
<br/>
- 교육 카테고리 전체 검색 api 입니다.
- 간단하게 findAll 조회 후, sorting 만 id 기준으로 적용되었습니다.
- securiy 경로는, 이미 allowed 되어있어, 별도로 추가하지 않았습니다.
<br/>
<br/>
<br/>

[FEAT] : #CE-1 교육 카테고리 검색

---

src/main/java/ssammudan/cotree/domain/resume/dto/ResumeResponse.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java

- resumeId 랑 techstacksId 추가
<br/>
#120 
<br/>
- 채용 전체 조회시 반환값 추가했습니다 (resumeId, techstacks id)
<br/>
<br/>
<br/>

[refactor] 채용 전체 조회시 반환값 추가

---

src/main/java/ssammudan/cotree/domain/education/techtube/controller/TechTubeController.java
src/main/java/ssammudan/cotree/domain/education/techtube/dto/TechTubeResponse.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeService.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeServiceImpl.java
src/main/java/ssammudan/cotree/global/converter/DurationToLongConverter.java
src/main/java/ssammudan/cotree/model/education/techtube/techtube/entity/TechTube.java
src/main/java/ssammudan/cotree/model/education/techtube/techtube/repository/TechTubeRepositoryCustom.java
src/main/java/ssammudan/cotree/model/education/techtube/techtube/repository/TechTubeRepositoryImpl.java
src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
src/test/java/ssammudan/cotree/model/education/techtube/category/repository/TechTubeEducationCategoryRepositoryTest.java

<br/>
#130 
<br/>
- 조회 방법 queryDSL 로 변경
- 회원의 상태 (결제, 좋아요 등)에 따라 서브쿼리 작성
- 구매 하지 않았을 경우, 영상 재생용 풀버전 url 은 배포되지 않도록 수정 (service 로직)
- `Duration` 타입 사용하지 않도록 변경 (converter 임시로 deprecated 설정)
- viewCount 증가 방법, community 와 동일하게 가져갈 예정으로, 임시 삭제 #39 
<br/>
<br/>
<br/>

[REFACTOR] : TechTube 상세 조회 리팩토링

---

src/main/java/ssammudan/cotree/domain/email/service/EmailService.java
src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
src/main/java/ssammudan/cotree/domain/phone/service/SmsService.java

<br/>
closes #145
<br/>
- redis 참조 key값 변경
<br/>
<br/>
<br/>

[Bug] 회원가입 오류

---

src/main/java/ssammudan/cotree/domain/email/service/EmailService.java
src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
src/main/java/ssammudan/cotree/domain/phone/service/SmsService.java
src/main/java/ssammudan/cotree/global/config/SecurityConfig.java

<br/>
카카오 로그인이 리다렉트로 정보를 받아올 때 경로를 열어주지 않아서 프론트엔드에서 접근을 할 수 없는 이슈가 있었습니다.
<br/>
- 리다이렉트 경로를 permitAll() 추가해줬습니다.
<br/>
<br/>
<br/>

[BUG] : 카카오 로그인 접근권한 허용

---

src/main/java/ssammudan/cotree/domain/resume/dto/ResumeResponse.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
src/main/resources/db/seed/dev/R__I_insert_resume_seed.sql
src/main/resources/db/seed/dev/R__J_insert_resume_position_seed.sql

<br/>
#153 
<br/>
- 조회 시 viewcount 반환값 누락 부분 추가
- dev seed 데이터 변경 및 추가
<br/>
쌈무단 Cotree 더미 데이터에는 resume 데이터가 정상적으로 들어가 있습니다 dev 의 seed 데이터만 문제라 변경하였습니다
<br/>
<br/>

[REFACTOR] 채용 지원 조회 반환값에 viewcount 누락

---

src/main/java/ssammudan/cotree/infra/payment/toss/TossPaymentHttpClient.java
src/main/resources/config/dev/application-dev_auth.yml
src/main/resources/config/prod/application-prod_auth.yml
src/test/resources/config/test/application-test_auth.yml

<br/>
close #156 
<br/>
- application.yml 내 토스페이먼츠 API 키 설정 추가
- TossPaymentHttpClient 내 API 키 파라미터 변경
<br/>
<br/>
<br/>

[BUG] TossPayments API 키 설정 추가

---

src/main/java/ssammudan/cotree/domain/project/controller/ProjectController.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectService.java
src/main/java/ssammudan/cotree/domain/project/service/ProjectServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/project/membership/entity/ProjectMembership.java
src/main/java/ssammudan/cotree/model/project/membership/repository/ProjectMembershipRepository.java

<br/>
#161 
<br/>
- 로그인한 회원만 프로젝트에 참가 신청할 수 있도록 구현
- 프로젝트 생성자는 참가 신청을 할 수 없도록 구현
- 이미 해당 프로젝트에 참가 신청한 회원은 중복 신청할 수 없도록 구현
- 프로젝트가 모집중일 때만 참가 신청이 가능하도록 조건 추가
<br/>

[FEAT] #PTDA-1 프로젝트 참가 신청

---

src/main/java/ssammudan/cotree/global/config/SecurityConfig.java

<br/>
#171 
<br/>
- CORS 설정에서 PATCH 메서드 누락되어 있었던 부분을 추가했습니다.
<br/>

[BUG] CORS 허용 메서드에 PATCH 추가

---

.github/workflows/gemini_code_review.yml

<br/>
#140 
<br/>
- dev 브랜치로 PR 생성 시 자동 리뷰가 작동하는 GitHub Actions 워크플로우 작성
- 원래는 라인 단위 코드 분석 및 리뷰를 시도했지만, API 사용상 제약으로 인해 파일 단위 리뷰로 전환
- 대부분 라인에 comment가 잘 달리지만, 특정 경우 실패 케이스 존재
- Gemini 유료 버전 사용 시 해결 가능성 있음
- 프롬프트 강화
- 파일단위로 코드리뷰를 진행하는 만큼 프롬프트를 명확하게 기재
- 워크플로우는 pull_request 이벤트 시에만 작동하도록 트리거 설정
- Gemini API를 활용해 변경된 파일 내용을 분석하고, 자동으로 리뷰 코멘트를 생성
- 개인 repository에서 정상 동작 확인 (첨부 이미지 참고: 문제 상황 → 결과물)
- 실제 운영에 도움이 되지 않는다고 판단되면 해당 워크플로우는 추후 정리할 계획입니다.
<br/>
문제 상황
결과물

[FEAT] #IGC-1 Gemini API 기반 GitHub Actions 리뷰 자동화 도입

---

src/main/java/ssammudan/cotree/domain/member/controller/MemberController.java
src/main/java/ssammudan/cotree/domain/member/dto/signup/MemberSignupRequest.java
src/main/java/ssammudan/cotree/domain/member/service/MemberService.java
src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/member/member/entity/Member.java
src/main/java/ssammudan/cotree/model/member/member/type/MemberRole.java
src/test/java/ssammudan/cotree/domain/member/service/MemberServiceTest.java
src/test/java/ssammudan/cotree/integration/factory/MemberDataFactory.java

<br/>
closes #125 
<br/>
- 비밀번호 변경 기능 구현(이메일 인증)
- MemberService 단위 테스트 보완
- 회원가입 시 Role반영(Front요청)
<br/>
<br/>
<br/>

[Feat] : #MRP-1 비밀번호 변경 구현

---

src/main/java/ssammudan/cotree/domain/member/dto/info/MemberInfoResponse.java

<br/>
this pr closes #183 
<br/>
- responseData 추가(profileImgUrl)
<br/>
<br/>
<br/>

[FEAT] : 회원 조회 데이터에 profileImgUrl 추가

---

src/main/java/ssammudan/cotree/domain/project/project/controller/ProjectController.java
src/main/java/ssammudan/cotree/domain/project/project/dto/ProjectLikeListResponse.java
src/main/java/ssammudan/cotree/domain/project/project/service/ProjectService.java
src/main/java/ssammudan/cotree/domain/project/project/service/ProjectServiceImpl.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/project/project/mapper/ProjectMapper.java
src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryCustom.java
src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java
src/main/java/ssammudan/cotree/model/project/project/repository/helper/ProjectQueryHelper.java
src/main/java/ssammudan/cotree/model/project/project/repository/support/ProjectQuerySupport.java
src/test/java/ssammudan/cotree/integration/DataJpaTestSupporter.java

<br/>
#190 
<br/>
- 프로젝트 좋아요 글 목록 조회
- projectQueryHelper -> support, mapper로 분리
<br/>

[FEAT] #PTL-1 프로젝트 좋아요 글 목록 조회

---

src/main/java/ssammudan/cotree/domain/member/service/MemberServiceImpl.java

<br/>
<br/>
- transactional 범위에선 save()는 error를 뱉지 않는 이슈가 있었습니다. flush를 통해 DB로 commit이전에 넘겨서 예외를 먼저 받도록 수정했습니다.
- 수정 전에는 GlobalExceptionHandler에서 catch해서 500에러가 발생했지만 수정 후에는 catch로 잡을 수 있게 되어 400에러가 정상적으로 발생되었습니다.
<br/>
<br/>
<br/>

refactor: Transaction 예외처리 실패 해결

---

src/main/java/ssammudan/cotree/domain/education/techtube/controller/TechTubeController.java
src/main/java/ssammudan/cotree/domain/education/techtube/dto/TechTubeResponse.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeService.java
src/main/java/ssammudan/cotree/domain/education/techtube/service/TechTubeServiceImpl.java
src/main/java/ssammudan/cotree/global/response/SuccessCode.java
src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryCustom.java
src/main/java/ssammudan/cotree/model/common/like/repository/LikeRepositoryImpl.java

<br/>
#199 
<br/>
- TechTube 좋아요 글 목록 조회 기능 구현
- Transaction 관리 누락 된, 메서드 추가 설정 (`getTechTubeLikeList0` 메서드)
<br/>
<br/>
<br/>

[FEAT] #ETL-2 TechTube 좋아요 글 목록 조회

---

src/main/java/ssammudan/cotree/domain/education/techbook/controller/TechBookController.java
src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookRequest.java
src/main/java/ssammudan/cotree/domain/education/techbook/dto/TechBookResponse.java
src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookService.java
src/main/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceImpl.java
src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
src/main/java/ssammudan/cotree/domain/payment/controller/PaymentController.java
src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java
src/main/java/ssammudan/cotree/domain/review/controller/TechEducationReviewController.java
src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewRequest.java
src/main/java/ssammudan/cotree/domain/review/dto/TechEducationReviewResponse.java
src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewService.java
src/main/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceImpl.java
src/main/java/ssammudan/cotree/global/response/PageResponse.java
src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryCustom.java
src/main/java/ssammudan/cotree/model/education/techbook/techbook/repository/TechBookRepositoryImpl.java
src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryCustom.java
src/main/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryImpl.java
src/test/java/ssammudan/cotree/domain/education/techbook/controller/TechBookControllerTest.java
src/test/java/ssammudan/cotree/domain/education/techbook/service/TechBookServiceTest.java
src/test/java/ssammudan/cotree/domain/review/controller/TechEducationReviewControllerTest.java
src/test/java/ssammudan/cotree/domain/review/service/TechEducationReviewServiceTest.java
src/test/java/ssammudan/cotree/model/review/review/repository/TechEducationReviewRepositoryTest.java

<br/>
close #207 
<br/>
- TechBook 목록 조회 에러 수정
- educationId 파라미터가 없을 때 발생하는 에러 수정
- 교육 컨텐츠 리뷰(TechEducationReview) 응답에 평점(avgRating) 필드 추가
- 요청/응답 DTO 이름 수정(리팩토링)
<br/>
<br/>
<br/>

[BUG] TechBook 조회 에러 수정 등

---

src/main/java/ssammudan/cotree/domain/community/dto/valid/CommunityContent.java
src/test/java/ssammudan/cotree/domain/community/dto/CommunityRequestTest.java

<br/>
#1
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
<br/>

[BUG] Community 글 작성 내용, 최대 범위 추가

---

src/main/java/ssammudan/cotree/global/config/SecurityConfig.java

<br/>
#214 
<br/>
아이디 찾기 api 인증 및 접근 권한 설정이 누락
<br/>
<br/>
<br/>

[BUG] 아이디 찾기 security 설정 누락

---

src/main/java/ssammudan/cotree/domain/project/project/service/ProjectServiceImpl.java
src/main/java/ssammudan/cotree/global/response/ErrorCode.java
src/main/java/ssammudan/cotree/global/util/ImageValidator.java

<br/>
#218 
<br/>
- 프로젝트 생성시 이미지 타입 validator 구현
- MIME 타입 사용
<br/>

[FIX] 프로젝트 이미지 업로드

---

src/main/java/ssammudan/cotree/model/project/project/repository/ProjectRepositoryImpl.java

<br/>
#222 
<br/>
- null 조건 확인 추가

[FIX] 좋아요 누른 프로젝트 조회

---

src/main/java/ssammudan/cotree/domain/order/facade/OrderFacade.java
src/main/java/ssammudan/cotree/domain/payment/dto/PaymentResponse.java
src/main/java/ssammudan/cotree/domain/payment/service/PaymentService.java
src/main/java/ssammudan/cotree/domain/payment/service/PaymentServiceImpl.java

<br/>
close #232 
<br/>
- 결제 결과 응답에 리다이렉트 필드 추가
- 컨텐츠 ID(itemId) 및 컨텐츠 타입(educationType)
- PaymentService 코드 리팩토링
<br/>
<br/>
<br/>

 [FEAT] 결제 응답 정보에 리다이렉트용 데이터 필드 추가

---

src/main/java/ssammudan/cotree/domain/resume/dto/ResumeResponse.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/ResumeRepositoryQueryDslImpl.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumeBasicInfoDto.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumePositionDto.java
src/main/java/ssammudan/cotree/model/recruitment/resume/resume/repository/dto/ResumeTechStackDto.java

<br/>
#240 
<br/>
- 귀찮아서 미뤘던 조회용 쿼리의 중간 Dto 생성
<br/>
<br/>
<br/>

[REFACTOR] 이력서 조회 쿼리 중간 DTO 생성

---

.gitignore
build.gradle
docker/database/db-docker-compose.yml
docker/database/mysql/init.sh
docker/monitoring/monitoring-docker-compose.yml
docker/monitoring/prometheus.yml
src/main/java/ssammudan/cotree/global/config/SecurityConfig.java
src/main/resources/config/dev/application-dev_server.yml
terraform/main.tf

<br/>
#
<br/>
- 데이터 베이스 서버 구축
<br/>
<br/>
<br/>

[FEAT] : 데이터베이스 분리

---

src/main/resources/config/dev/application-dev_server.yml
src/main/resources/config/prod/application-prod_server.yml

- jvm 관련 metrics 추가 output 진행 설정
<br/>
#250 
<br/>
- 기능에서 어떤 부분이
- 구현되었는지 설명해주세요
<br/>
<br/>
<br/>

[REFACTOR] : Enable JMX Tomcat metrics 추가

---

src/main/resources/config/dev/application-dev_db.yml
src/main/resources/config/prod/application-prod_db.yml

<br/>
#253
<br/>
- Hikari CP pool max size 변경
- 10 -> 5
<br/>
<br/>
<br/>

[REFACTOR] : Hikari CP pool max size 변경
